import os , time
os.system ("clear")
print ("Hello")
time.sleep (1)
print ("please complete the answer")
time.sleep (1)
name = input ("the name: ")
time.sleep (1.5)
print ("")
number = input ("the number: ")
time.sleep (1.5)
print ("")
edge = input ("edge: ")
time.sleep (1.5)
print ("")
an_password = input ("any password: ")
time.sleep (1.5)
print ("")
print ("@made by clay88")
print ("")
print ("[$]now i will write a some passwords")
time.sleep(0.3)
print ("[1] " + name + name )
time.sleep(0.3)
print ("[2] " + name + 12345)
time.sleep(0.3)
print ("[3] " + name + number)
time.sleep(0.3)
print ("[4] " + name + edge)
time.sleep(0.3)
print ("[5] " + name + an_password)
time.sleep(0.3)
print ("[6] " + number)
time.sleep(0.3)
print ("[7] " + name + 1123455)
time.sleep(0.3)
print ("[8] " + 1123455)
time.sleep(0.3)
print ("[9] " + 1234512345)
time.sleep(0.3)
print ("[10] " + name + 1122334455)
time.sleep(0.3)
print ("[11] " + an_password)
time.sleep(0.3)
print ("[12] " + an_password + name)
time.sleep(0.3)
print ("[13] " + 1122334455
time.sleep(0.3)
print ("[14] " + admin123)
print ("[15] " + Admin5)
print ("")
print ("")
print ("soory but we dont have another passwords we will upgrade the tool later And thanks")
time.sleep(3)
print ("::made by clay88::")
print ("thanks For use my tool")
print ("")
print ("my youtube chanel's link will appear after 10 secound")
print ("")
time.sleep(11)
print ("https://www.youtube.com/channel/UC0eT-elLM5LoHuotz5vqNYg/videos")




